export const data = [
    { category: 'Engineering', branch: 'Electrical', year: '1', subject: 'Physics', notesLink: 'http://', author: 'Muhammed Safwan' },
    { category: 'Engineering', branch: 'Electrical', year: '1', subject: 'Chemistry', notesLink: 'http://', author: 'Alice Johnson' },
    { category: 'Engineering', branch: 'Electrical', year: '2', subject: 'Mathematics', notesLink: 'http://', author: 'Jack Davis' },
    { category: 'Engineering', branch: 'Electrical', year: '2', subject: 'Circuit Theory', notesLink: 'http://', author: 'Emma Brown' },
    { category: 'Engineering', branch: 'Electrical', year: '3', subject: 'Electromagnetism', notesLink: 'http://', author: 'Sophia Clark' },
    { category: 'Engineering', branch: 'Electrical', year: '3', subject: 'Signal Processing', notesLink: 'http://', author: 'Liam Smith' },
    { category: 'Engineering', branch: 'Electrical', year: '4', subject: 'Control Systems', notesLink: 'http://', author: 'Noah Wilson' },
    { category: 'Engineering', branch: 'Electrical', year: '4', subject: 'Power Systems', notesLink: 'http://', author: 'Olivia Martinez' },

    { category: 'Engineering', branch: 'Mechanical', year: '1', subject: 'Thermodynamics', notesLink: 'http://', author: 'Ethan Thompson' },
    { category: 'Engineering', branch: 'Mechanical', year: '1', subject: 'Fluid Mechanics', notesLink: 'http://', author: 'Isabella Anderson' },
    { category: 'Engineering', branch: 'Mechanical', year: '2', subject: 'Mechanics of Materials', notesLink: 'http://', author: 'Mason Taylor' },
    { category: 'Engineering', branch: 'Mechanical', year: '2', subject: 'Dynamics', notesLink: 'http://', author: 'Ava Hernandez' },
    { category: 'Engineering', branch: 'Mechanical', year: '3', subject: 'Heat Transfer', notesLink: 'http://', author: 'Lucas Robinson' },
    { category: 'Engineering', branch: 'Mechanical', year: '3', subject: 'Machine Design', notesLink: 'http://', author: 'Mia Walker' },
    { category: 'Engineering', branch: 'Mechanical', year: '4', subject: 'Manufacturing Processes', notesLink: 'http://', author: 'Oliver Wright' },
    { category: 'Engineering', branch: 'Mechanical', year: '4', subject: 'CAD/CAM', notesLink: 'http://', author: 'Charlotte Lee' },

    { category: 'Engineering', branch: 'Civil', year: '1', subject: 'Surveying', notesLink: 'http://', author: 'James Hall' },
    { category: 'Engineering', branch: 'Civil', year: '1', subject: 'Building Materials', notesLink: 'http://', author: 'Amelia Young' },
    { category: 'Engineering', branch: 'Civil', year: '2', subject: 'Structural Analysis', notesLink: 'http://', author: 'Benjamin King' },
    { category: 'Engineering', branch: 'Civil', year: '2', subject: 'Fluid Mechanics', notesLink: 'http://', author: 'Harper Scott' },
    { category: 'Engineering', branch: 'Civil', year: '3', subject: 'Geotechnical Engineering', notesLink: 'http://', author: 'Henry Green' },
    { category: 'Engineering', branch: 'Civil', year: '3', subject: 'Transportation Engineering', notesLink: 'http://', author: 'Ella Adams' },
    { category: 'Engineering', branch: 'Civil', year: '4', subject: 'Environmental Engineering', notesLink: 'http://', author: 'Jackson Baker' },
    { category: 'Engineering', branch: 'Civil', year: '4', subject: 'Construction Management', notesLink: 'http://', author: 'Avery Nelson' },

    { category: 'Engineering', branch: 'Computer', year: '1', subject: 'Programming Fundamentals', notesLink: 'http://', author: 'Samuel Carter' },
    { category: 'Engineering', branch: 'Computer', year: '1', subject: 'Discrete Mathematics', notesLink: 'http://', author: 'Sofia Mitchell' },
    { category: 'Engineering', branch: 'Computer', year: '2', subject: 'Data Structures', notesLink: 'http://', author: 'David Perez' },
    { category: 'Engineering', branch: 'Computer', year: '2', subject: 'Algorithms', notesLink: 'http://', author: 'Chloe Roberts' },
    { category: 'Engineering', branch: 'Computer', year: '3', subject: 'Operating Systems', notesLink: 'http://', author: 'Lucas Edwards' },
    { category: 'Engineering', branch: 'Computer', year: '3', subject: 'Database Management', notesLink: 'http://', author: 'Zoe Turner' },
    { category: 'Engineering', branch: 'Computer', year: '4', subject: 'Software Engineering', notesLink: 'http://', author: 'Gabriel Phillips' },
    { category: 'Engineering', branch: 'Computer', year: '4', subject: 'Web Development', notesLink: 'http://', author: 'Lily Campbell' }
];
